# Generated by Django 2.1 on 2019-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
