# Generated by Django 2.1 on 2019-04-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='readed_num',
        ),
    ]
